### PR TITLE
updated unified inventory to have catgories

### PR DESCRIPTION
**Pull request by oversword**
Fixes https://github.com/BlockySurvival/issue-tracker/issues/286

Categories!

### CODE REVIEW

**Comment by luk3yx** [comment]
Mods that use unified_inventory (such as skinsdb and unified_inventory_plus) will need to be updated as well because of the changes made in https://github.com/minetest-mods/unified_inventory/pull/168.

**Comment by oversword** [comment]
Understood, Ill do that in this MR, just doing the categories for our mods ATM

**Comment by oversword** [comment]
@luk3yx I think that's done

**Comment by oversword** [comment]
Nobody seems to use the streets mod or will tell me how it works, I will fix it when I hear a complaint

**Pull request merged**
